### PR TITLE
testtest

### PR DESCRIPTION
**Pull request by joelpolanco**

### CODE REVIEW

**Comment by dadrivr** [comment]
What's the pull request for?  It looks like it changed the .tar file.  We've since updated the .tar file, though, so it would be better to modify the code of other files rather than the compiled .tar file.

**Comment by joelpolanco** [comment]
Apologies, I am still learning. Meant to fork. I eventually got the package loaded...I had a lot of missing dependencies (I had to install packages manually on my windows machine). One problem though, I still do not see add-ins. I tried to troubleshoot that last week to no avail. Has anyone else had this problem?

**Comment by dadrivr** [comment]
Did you install the `ffanalytics` package via devtools or tarball?  For more info, see the Installation section here:
http://fantasyfootballanalytics.net/2016/06/ffanalytics-r-package-fantasy-football-data-analysis.html

**Comment by joelpolanco** [comment]
Tarball. I continued to receive errors from devtools. I reviewed the thread and left several comments/questions. I was able to get the package loaded but like i said, specifically - "addins" are not showing up in my toolbar.

**Comment by dadrivr** [comment]
What happens when you type `library("ffanalytics")`?

**Comment by joelpolanco** [comment]
This shows in the console :100: 

> library("ffanalytics")
Loading required package: shiny
Loading required package: miniUI
Warning messages:
1: package ‘shiny’ was built under R version 3.3.1 
2: package ‘miniUI’ was built under R version 3.3.1 
>


Nothing else happens, I don't see the add-ins toolbar as Rstudio website suggests should happen: https://rstudio.github.io/rstudioaddins/

**Comment by dadrivr** [comment]
Make sure you're using the latest version of R-studio, as well.  Could you give us the output from `sessionInfo()` after loading the `ffanalytics` package which will show the environment and other information from R?

**Comment by joelpolanco** [comment]
I updated R Studio, R and all packages. Now i get this error:

> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.3.1
> library("ffanalytics")
Loading required package: shiny
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘digest’
Error: package ‘shiny’ could not be loaded

**Comment by joelpolanco** [comment]
i just reinstalled shiny, then got the same error for plyr, looks like i need to manually reinstall all the packages. I'll check back in later

**Comment by joelpolanco** [comment]
Found the issue with R Studio via their support forum. The latest version of R studio was installed on my machine but it installed to a non-standard location. The exe icon on my desktop was not overwritten to the new location and as such, i was loading an old version of R Studio. Just loaded ffanalytics and its working (addins are showing now). Sorry again for the pull request and thanks for your help.

**Comment by dadrivr** [comment]
Glad to hear, thanks for the update!

**Pull request closed without merging**
